export interface Project {
  id: string;
  title: string;
  subtitle: string;
  status: "live" | "concept";
  liveUrl?: string;
  targetCompanies: string[];
  techStack: string[];
  dataSources: string[];
  description: string;
  location: [number, number]; // [lng, lat]
  icon: string;
  category: string;
  image?: string;
}

export const projects: Project[] = [
  {
    id: "weather-explorer",
    title: "AI Weather Model Explorer",
    subtitle: "Compare AI weather models against real-world observations in real time",
    status: "live",
    liveUrl: "https://weather-model-explorer.vercel.app",
    image: "/screenshots/weather-explorer.png",
    targetCompanies: ["Jua.ai", "Beyond Weather", "Tomorrow.io", "Zeus AI"],
    techStack: ["Next.js", "MapLibre GL", "Recharts", "TypeScript", "Tailwind CSS", "Open-Meteo API"],
    dataSources: ["Open-Meteo Forecast API", "Open-Meteo Archive API", "Geocoding API"],
    description: "Interactive dashboard that fetches forecasts from ECMWF, GFS, ICON, and Open-Meteo's AI model, compares them against observed conditions, and visualizes forecast accuracy with RMSE, MAE, and bias metrics. Includes a precomputed spatial skill map showing which model performs best across the continental US.",
    location: [-98.5, 39.8],
    icon: "cloud-sun",
    category: "Weather AI",
  },
  {
    id: "satellite-change-detection",
    title: "Satellite Change Detection Dashboard",
    subtitle: "Detect aquaculture expansion from Sentinel-2 imagery using AI embeddings",
    status: "concept",
    targetCompanies: ["Clay", "Zeus AI", "Pano AI"],
    techStack: ["FastAPI", "pystac-client", "rasterio", "NumPy", "Clay Model", "Next.js", "Mapbox GL"],
    dataSources: ["Microsoft Planetary Computer STAC", "Sentinel-2 L2A", "Clay Foundation Model"],
    description: "Dashboard using Sentinel-2 satellite imagery to detect land-use changes over time. Computes NDWI to identify new water bodies, with an advanced mode using Clay foundation model embeddings for unsupervised change detection. Split-view map comparison with accuracy validation against known aquaculture facility locations.",
    location: [120.5, 31.2],
    icon: "satellite",
    category: "Remote Sensing",
  },
  {
    id: "climate-pipeline",
    title: "Xarray/Zarr Climate Data Pipeline",
    subtitle: "Cloud-native climate analysis from ERA5 reanalysis data",
    status: "concept",
    targetCompanies: ["Earthmover", "Tomorrow.io", "Jua", "Zeus AI"],
    techStack: ["Xarray", "Zarr", "Dask", "FastAPI", "Next.js", "Mapbox GL", "D3.js"],
    dataSources: ["ERA5 Reanalysis (CDS)", "WeatherBench2 (Google Cloud)", "NCEP/NCAR Reanalysis"],
    description: "End-to-end pipeline loading ERA5 climate reanalysis into cloud-native Zarr format, computing temperature trends, extreme heat frequency, and precipitation anomalies. Serves results through a FastAPI backend consumed by a React frontend with animated anomaly playback and decade comparison views.",
    location: [10.0, 48.0],
    icon: "database",
    category: "Data Engineering",
  },
  {
    id: "wildfire-risk",
    title: "Real-Time Wildfire Risk Map",
    subtitle: "NASA FIRMS active fire data fused with live weather for dynamic risk assessment",
    status: "concept",
    targetCompanies: ["Pano AI", "Tomorrow.io", "Jua"],
    techStack: ["Next.js", "Mapbox GL", "Deck.gl", "Turf.js", "Recharts", "Tailwind CSS"],
    dataSources: ["NASA FIRMS", "Open-Meteo Weather API", "NOAA HRRR-Smoke", "NIFC Perimeters"],
    description: "Real-time wildfire monitoring dashboard fusing MODIS/VIIRS active fire detections with current weather (wind, humidity, temperature) to compute a dynamic Fire Weather Index. Features animated wind particle visualization for fire spread prediction and user-defined alert zones.",
    location: [-119.5, 37.8],
    icon: "flame",
    category: "Hazard Monitoring",
  },
  {
    id: "weather-foundation-model",
    title: "Fine-Tune Weather Foundation Model",
    subtitle: "Regional fine-tuning of FourCastNet with evaluation dashboard",
    status: "concept",
    targetCompanies: ["Beyond Weather", "Jua", "Zeus AI"],
    techStack: ["PyTorch", "earth2mip", "Xarray", "Zarr", "W&B", "Next.js", "Recharts"],
    dataSources: ["ERA5 Reanalysis", "NVIDIA FourCastNet", "WeatherBench2"],
    description: "End-to-end ML pipeline fine-tuning NVIDIA's FourCastNet weather model on US Northeast regional temperature data. Benchmarks against base model and climatology baseline across multiple lead times, with a web dashboard displaying skill scores, spatial error maps, and case study forecasts.",
    location: [-72.0, 42.5],
    icon: "brain",
    category: "ML Engineering",
  },
  {
    id: "weather-explainer",
    title: "Interactive Severe Weather Explainer",
    subtitle: "Immersive scroll-driven narratives teaching the science of weather",
    status: "concept",
    targetCompanies: ["Tomorrow.io", "The Weather Company", "DTN", "Climavision"],
    techStack: ["Next.js", "Scrollama", "Mapbox GL", "D3.js", "Framer Motion", "Canvas API"],
    dataSources: ["NOAA/NWS", "ECMWF", "IPCC", "AMS Journals", "Peer-reviewed literature"],
    description: "Immersive educational website teaching atmospheric science through interactive storm life-cycle narratives. Each severe weather type — tornadoes, hurricanes, derechos — is taught by following a real historic event from genesis to aftermath with scroll-driven animations, radar loops, and annotated diagrams.",
    location: [-95.0, 35.0],
    icon: "tornado",
    category: "Science Communication",
  },
  {
    id: "model-explainer",
    title: "Climate & Weather Model Explainer",
    subtitle: "How weather prediction works — from numerical equations to AI revolution",
    status: "concept",
    targetCompanies: ["Tomorrow.io", "Climavision", "Jua.ai", "Zeus AI", "Google DeepMind", "ECMWF"],
    techStack: ["Next.js", "Scrollama", "D3.js", "Three.js", "Mapbox GL", "Canvas API"],
    dataSources: ["ECMWF Documentation", "NOAA/NWS", "GraphCast/GenCast papers", "ERA5"],
    description: "Scroll-driven educational site walking users through the full lifecycle of a weather forecast: observation collection, atmospheric discretization, equation solving, chaos theory limits on predictability, and how modern AI models from Google DeepMind and NVIDIA are disrupting the field.",
    location: [11.8, 51.4],
    icon: "grid",
    category: "Science Communication",
  },
  {
    id: "satellite-monitoring",
    title: "Satellite Weather Monitoring Dashboard",
    subtitle: "Multi-sensor satellite data fusion for environmental intelligence",
    status: "concept",
    targetCompanies: ["Tomorrow.io", "Pano AI", "Climavision", "Planet Labs", "NOAA/NESDIS"],
    techStack: ["FastAPI", "pystac-client", "rasterio", "Xarray", "Next.js", "Mapbox GL", "Deck.gl"],
    dataSources: ["NASA FIRMS", "Sentinel-2 (STAC)", "GOES-16/18 (AWS)", "Open-Meteo", "NOAA HRRR-Smoke"],
    description: "Full-stack monitoring platform fusing MODIS/VIIRS fire detections, Sentinel-2 burn scar analysis (dNBR), GOES geostationary imagery, and weather data. Demonstrates understanding of the full satellite observation stack — from photon to forecast — with educational panels explaining orbital mechanics and spectral physics.",
    location: [-105.0, 40.0],
    icon: "satellite-dish",
    category: "Remote Sensing",
  },
  {
    id: "canopy-equity",
    title: "Urban Tree Canopy Equity Explorer",
    subtitle: "Meta's 1m canopy height maps reveal environmental justice gaps",
    status: "concept",
    targetCompanies: ["Planet Labs", "Pachama", "Vibrant Planet", "Meta AI", "American Forests"],
    techStack: ["rasterio", "GeoPandas", "rasterstats", "D3.js", "Scrollama", "Mapbox GL", "PMTiles"],
    dataSources: ["Meta/WRI Canopy Height (S3)", "US Census ACS", "CDC SVI", "Landsat 8/9 Thermal", "USFS UTC"],
    description: "Interactive tool using Meta's AI-derived 1-meter canopy height maps to analyze how tree cover correlates with income, race, and heat vulnerability at census tract level. Features bivariate choropleths, scatterplots with brushing/linking, a tree planting prioritization tool, and scrollytelling narratives for city case studies.",
    location: [-112.0, 33.4],
    icon: "tree",
    category: "Environmental Justice",
  },
  {
    id: "climate-adaptation",
    title: "Climate Adaptation Atlas",
    subtitle: "How climate hazards are intensifying — and what communities are doing about it",
    status: "concept",
    targetCompanies: ["First Street Foundation", "Jupiter Intelligence", "One Concern", "Moody's RMS"],
    techStack: ["Xarray", "Pandas", "scikit-learn", "Scrollama", "D3.js", "Mapbox GL", "PMTiles"],
    dataSources: ["NOAA nClimDiv", "NOAA Storm Events", "NASA NEX-GDDP-CMIP6", "FEMA NRI", "Georgetown Adaptation Clearinghouse"],
    description: "Maps intensifying climate hazards — extreme heat, flooding, severe storms — across US counties with observed trends and CMIP6 future projections. Pairs worsening exposure with real adaptation case studies and computes an 'adaptation gap' score identifying underprotected communities.",
    location: [-90.0, 30.0],
    icon: "shield",
    category: "Climate Risk",
  },
  {
    id: "flash-flood",
    title: "Urban Flash Flood Early Warning System",
    subtitle: "Google Groundsource-inspired hyperlocal flash flood forecasting",
    status: "concept",
    targetCompanies: ["Google Earth AI", "Jupiter Intelligence", "First Street", "One Concern", "Tomorrow.io"],
    techStack: ["XGBoost", "Xarray", "richdem", "GeoPandas", "Next.js", "Mapbox GL", "D3.js", "SWR"],
    dataSources: ["NOAA MRMS", "NOAA NWM", "USGS 3DEP LiDAR", "NLCD Impervious Surface", "CDC SVI", "FEMA NFIP Claims"],
    description: "Combines Google's Groundsource methodology (AI-driven flood prediction without gauge networks) with local urban context: terrain analysis from LiDAR DEMs, impervious surface mapping, and social vulnerability scoring. Bivariate choropleth shows compound risk (flood hazard x social vulnerability) with real-time MRMS radar and precipitation threshold monitoring.",
    location: [-95.3, 29.7],
    icon: "droplets",
    category: "Hazard Monitoring",
  },
];

export const skillCategories = [
  {
    title: "Frontend & Mapping",
    skills: [
      "Next.js / React",
      "TypeScript",
      "Tailwind CSS",
      "MapLibre GL / Mapbox GL",
      "D3.js / Recharts",
      "Deck.gl",
      "Scrollama",
      "PMTiles",
    ],
  },
  {
    title: "Data & ML",
    skills: [
      "Python",
      "Xarray / Zarr / NetCDF",
      "GeoPandas / rasterio",
      "PyTorch",
      "scikit-learn / XGBoost",
      "NumPy / SciPy / Pandas",
      "STAC / COG / Cloud-Native",
      "ERA5 / CMIP6",
    ],
  },
  {
    title: "Tools & Infrastructure",
    skills: [
      "FastAPI",
      "PostgreSQL / PostGIS",
      "Git / GitHub Actions",
      "Vercel / Railway",
      "Docker",
      "AWS S3 / GCS",
      "QGIS",
      "Jupyter / Colab",
    ],
  },
];
